# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

transaction:
  service:
    url: http://transaction-service:8082/api/transactions
