
# src/main/resources/application.yml
server:
  port:8080
spring:
  application:
    name:Account
  datasource:
    url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates or updates tables
    show-sql: true  # Show SQL statements in the log for debugging
