version: '3.8'

services:
  account-service:
    build:
      context: ./account
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "8080:8080"  # Map port 8080 in the container to 8081 on the host

  transaction-service:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "8082:8082"  # Map port 8080 in the container to 8082 on the host

networks:
  my_network:
    driver: bridge
