apiVersion : apps/v1
kind: Deployment
metadata:
  name: opencurrentaccount 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencurrentaccount
  template:
    metadata:
      labels:
        app: opencurrentaccount 
    spec:
      containers:
        - name: opencurrentaccount 
          image: openaccountcicd.azurecr.io/opencurrentaccount
          ports:
          - containerPort: 8080