apiVersion : apps/v1
kind: Deployment
metadata:
  name: transaction 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction 
    spec:
      containers:
        - name: transaction 
          image: openaccountacr.azurecr.io/transaction
          ports:
          - containerPort: 8082