# src/main/resources/application.yml
server:
  port:8081
spring:
  application:
    name:Account
  datasource:
    url: jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
